/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-screen h-screen overflow-x-auto bg-linear-default flex flex-col lg:flex-row-reverse items-center justify-center lg:justify-between lg:px-[170px]'>
        <div className='flex flex-col items-center gap-[16px] lg:items-end'>
          <p className='font-[700] text-4xl md:text-6xl text-center lg:text-right'>
            <span className='text-muted'>Imagine if had</span> <br></br>
            <span className='text-linear-mute'>Snapchat </span>
            <br></br>
            <span className='text-muted'>events.</span>
          </p>
          <p className='font-[300] text-base md:text-2xl non-italics w-8/12 text-center text-[#4F4F4F] lg:text-right'>
            Easily host and share events with your friends across any social
            media.
          </p>

          <Link href={'/create'}>
            <button
              type='button'
              className='bg-linear-mute rounded-[10px] px-[21px] md:px-[69.5px] py-[16px] text-[#fff] text-base font-[700] md:text-xl hidden lg:block mt-[52px]'
            >
              🎉 Create my event
            </button>
          </Link>
        </div>
        <div className='mt-[36px] mb-[34px] flex flex-col items-center'>
          <img
            loading='lazy'
            src='/assets/images/image.png'
            className='w-[165.63px] h-[292px] md:w-[311px] md:h-[548.27px] lg:w-[440px] lg:h-[775.69px] object-contain object-center'
            alt='React logo'
          />
          <div className='lg:hidden'>
            <Link href={'/create'}>
              <button
                type='button'
                className='bg-linear-mute rounded-[10px] px-[21px] md:px-[69.5px] py-[16px] text-[#fff] text-base font-[700] md:text-xl'
              >
                🎉 Create my event
              </button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
